appsite/appsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^bluehack/', include('bluehack.urls', namespace="bluehack")),
    url(r'^admin/', include(admin.site.urls)),
]

appsite/bluehack/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<username>\w+)/register/$', views.register, name='register'),
]

appsite/bluehack/models.py
from django.db import models
from django.contrib.auth.models import User


class Crisis(models.Model):
    """
    Data for a given crisis. See the sample output of the
    API we plan to use:
    http://reliefweb.int/help/api/advanced

    Here are all the fields they provide:
    http://reliefweb.int/help/api/field-definitions#disaster
    """

    rwid         = models.IntegerField() #ReliefWeb Id
    name         = models.CharField(max_length=200)
    url          = models.CharField(max_length=200)
    status       = models.CharField(max_length=8,
                                    choices=[
                                    ("alert", "alert"),
                                    ("current", "current"),
                                    ("past", "past")])
    glide        = models.CharField(max_length=100) # GUID
    countries    = models.CharField(max_length=256) # CSV of ISO3 country names (sorted alphabetically)
    # geo_lat      = models.FloatField()
    # geo_long     = models.FloatField()

    def defineFromReliefWebResponse(self, data):
        self.rwid = data["fields"]["id"]
        self.name = data["fields"]["name"]
        self.url = data["fields"]["url"]
        self.status = data["fields"]["status"]
        self.glide = data["fields"]["glide"]

        countries = []
        for c in data["fields"]["country"]:
            countries.append(c["iso3"])
        self.countries = "".join(countries)

class CrisisUser(models.Model):
    user       = models.OneToOneField(User, on_delete=models.CASCADE)
    cellphone  = models.CharField(max_length=10, default='')
    address    = models.CharField(max_length=100, default='')
    country    = models.CharField(max_length=10)

class CrisisUserPairs(models.Model):
    user       = models.ForeignKey(CrisisUser)
    crisis     = models.ForeignKey(Crisis)
    notified   = models.BooleanField(default=False)
    evacuating = models.BooleanField(default=False)
    responded  = models.BooleanField(default=False)

appsite/bluehack/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User   # fill in custom user info then save it
from bluehack.models import CrisisUser
from django.contrib.auth.forms import UserCreationForm

class CrisisUserForm(ModelForm):
	class Meta:
		model = CrisisUser
		exclude = ['user']

	# def save(self, commit = True):
	# 	user = super(MyRegistrationForm, self).save(commit = False)
	# 	user.email = self.cleaned_data['email']
	#
	# 	if commit:
	# 		user.save()
	#
	# 	return user

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password')

appsite/bluehack/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from models import CrisisUser
from forms import CrisisUserForm, UserForm
from django.forms.models import model_to_dict

def index(request):
	# Process the form data
	if request.method == "POST":
		crisisUserForm = CrisisUserForm(request.POST)
		userForm = UserForm(request.POST)
		assert crisisUserForm.is_valid()
		assert userForm.is_valid()
		if crisisUserForm.is_valid() and userForm.is_valid():
			crisisUserForm_data = crisisUserForm.cleaned_data
			userForm_data = userForm.cleaned_data
			new_user = User.objects.create_user(**userForm_data)
			new_user.save()
			crisis_user = CrisisUser.objects.create(user=new_user, **crisisUserForm_data)
			crisis_user.save()
			return HttpResponseRedirect(reverse('bluehack:register', args=(userForm_data['username'],)))

		return render(request, 'bluehack/index.html', {'error': 'Failed to register'})
	# Create a blank form if any other method
	else:
		crisisUserForm = CrisisUserForm()
		userForm = UserForm()
	return render(request, 'bluehack/index.html', {
		'error': '',
		'crisisUserForm': crisisUserForm,
		'userForm': userForm
		})

def register(request, username):
	user = User.objects.get(username=username)
	password = user.password
	email = user.email
	cellphone = user.crisisuser.cellphone
	address = user.crisisuser.address
	context = {
				'userProps': model_to_dict(user, fields=['username', 'password', 'email']),
				'crisisUserProps': model_to_dict(user.crisisuser)
			  }
	return render(request, 'bluehack/register.html', context)

appsite/bluehack/templates/bluehack/index.html
<!doctype html>
<html>
    <head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	</head>
	<body>
		<div>
			<h1>Bluehack</h1>
		</div>
		{% if not error %}
		<div>
			<form action="{% url 'bluehack:index' %}" method="post">
			{% csrf_token %}
				<h1><span class="label label-default">Account Creation</span></h1>
        {{ userForm }}
        {{ crisisUserForm }}
				<input type="submit" class="btn btn-lg btn-primary" value="Register">
			</form>
		</div>
		{% endif %}
		<div><h1>{{ error }}</h1></div>
	</body>
</html>

appsite/bluehack/templates/bluehack/register.html
<!doctype html>
<html>
    <head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	</head>
	<body>
		<div>
			<h1><span class="label label-info">{{ userProps.username }}</span> registered successfully with the following information</h1>
			<table class="table"><tbody>
        {% for key,value in userProps.items %}
        <tr>
          <td>{{ key }}</td><td>{{ value }}</td>
        <tr>
        {% endfor %}
        {% for key,value in crisisUserProps.items %}
        <tr>
          <td>{{ key }}</td><td>{{ value }}</td>
        <tr>
        {% endfor %}
			</tbody></table>
		</div>
</html>